config/routes.rb
Rails.application.routes.draw do
  resources :moves
  resources :types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pokemons#index'
  resources :pokemons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/move.rb
class Move < ApplicationRecord
  belongs_to :type, optional: true
  	has_many :pokemon_moves
	has_many :moves, through: :pokemon_moves
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	belongs_to :type, optional: true
	has_many :pokemon_moves
	has_many :moves, through: :pokemon_moves
end

app/models/pokemon_move.rb
class PokemonMove < ApplicationRecord
  belongs_to :pokemon
  belongs_to :move
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :pokemons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  def index
    @moves = Move.all
  end

  def show
  end

  def new
    @move = Move.new
  end

  def edit
  end

  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Le type a été créer avec succès.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Le type a été modifier avec succès.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Le type a été supprimer avec succès.' }
    end
  end

  private
    def set_move
      @move = Move.find(params[:id])
    end

    def move_params
      params.require(:move).permit(:name, :description, :type_id)
    end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
	before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

	def index
		@pokemons = Pokemon.paginate(page: params[:page], per_page: 1)
		.includes(:type)
	end

	def show
	end

	def new
		@pokemon = Pokemon.new
	end

	def create
		@pokemon = Pokemon.new pokemon_params
		if @pokemon.save
			redirect_to @pokemon
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pokemon.update pokemon_params
			redirect_to @pokemon
		else
			render 'edit'
		end
	end

	def destroy
		@pokemon.destroy
		redirect_to pokemons_path
	end

	private

	def set_pokemon
		@pokemon = Pokemon.find params[:id]
	end

	def pokemon_params
		params.require(:pokemon).permit(:name, :number, :level, :health_points, :type_id, move_ids: [])
	end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  def index
    @types = Type.all
  end

  def show
  end

  def new
    @type = Type.new
  end

  def edit
  end

  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Le type a été créer avec succès.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Le type a été modifier avec succès.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Le type a été supprimer avec succès.' }
    end
  end

  private
    def set_type
      @type = Type.find(params[:id])
    end

    def type_params
      params.require(:type).permit(:name, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/types_helper.rb
module TypesHelper
	def type_badge(type, label = type.name)
		link_to(type_badge_content(label, type.color), type).html_safe
	end

	def type_badge_content(label, color)
		raw "<span style='background-color: #{color}' class='badge'>
		#{label}
		</span>"
	end
end

app/views/home/index.html.erb
<h1>
	Ceci est la page d'accueil du projet
	<%= Rails.application.class.parent_name %> !
</h1>

<p>
	<%= link_to 'Liste des Pokemons', pokemons_path, class: 'btn btn-primary' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta hhtp-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" cotent="width=device-width, initial-scale=1">
	<link rel="shortcut icon" href="http://assets.pokemon.com/static2/_ui/img/favicon.ico" />
	<title>Pokedex</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/moves/_form.html.erb
<%= simple_form_for(@move) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<p>
  <%= link_to 'Pokemons', pokemons_path, class: 'btn btn-default' %>
  <%= link_to 'Types', types_path, class: 'btn btn-default' %>
  <%= link_to 'Moves', moves_path, class: 'btn btn-default' %>
</p>

<h1>Moves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= move.name %></td>
        <td><%= move.description %></td>
        <td><%= move.type %></td>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @move.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @move.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @move.type %>
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>

app/views/pokemons/_form.html.erb
<%= simple_form_for @pokemon do |f| %>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<%= f.input :name, label: 'Nom', class: 'form-control' %>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<%= f.input :number, label: 'Numéro', class: 'form-control' %>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<%= f.input :level, label: 'niveau', class: 'form-control' %>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<%= f.input :health_points, label: 'Point de vie', class: 'form-control' %>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<%= f.association :type, label: 'Type', class: 'form-control' %>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<%= f.association :moves, label: 'Attaques', as: :check_boxes, class: 'form-control' %>
		</p>
	</div>
</div>
<p>
	<%= f.submit submit , class: 'btn btn-primary' %> <!-- Préférer l'internationalisation pour le nom du bouton -->
</p>
<% end %>

app/views/pokemons/_moves_list.html.erb
<% if moves.any? %>
<%= raw moves.map { |m| link_to(m.name, m) }
.join(', ') %>
<% else %>
&empty;
<% end %>

app/views/pokemons/edit.html.erb
<h1>Édition d'un Pokemon</h1>

<%= render partial: 'form', locals: {submit: 'Modifier'} %> <!-- Préférer l'internationalisation pour le nom du bouton -->

<%= link_to 'Liste des Pokemons', pokemons_path, class: 'btn btn-primary' %>

app/views/pokemons/index.html.erb
<p>
	<%= link_to 'Pokemons', pokemons_path, class: 'btn btn-default' %>
	<%= link_to 'Types', types_path, class: 'btn btn-default' %>
	<%= link_to 'Moves', moves_path, class: 'btn btn-default' %>
</p>

<h1>Liste des Pokemons</h1>

<% if @pokemons.any? %>

<%= will_paginate @pokemons, renderer: BootstrapPagination::Rails %>

<table class="table">
	<thead>
		<tr>
			<td>Numéro</td>
			<td>Nom</td>
			<td>Type</td>
			<td>Attaques</td>
		</tr>
	</thead>
	<tbody>
		<% @pokemons.each do |pokemon| %>
		<tr>
			<td>#<%= sprintf '%03d', pokemon.number %></td>
			<td><%= pokemon.name %></td>
			<td><%= pokemon.type ? type_badge(pokemon.type) : '&empty;'.html_safe %></td>
			<td><%= render partial: 'moves_list', locals: {moves: pokemon.moves} %></td>
			<td><%= link_to 'Afficher', pokemon, class: 'btn btn-primary' %></td>
			<td><%= link_to 'Modifier', edit_pokemon_path(pokemon), class: 'btn btn-warning' %></td>
			<td><%= link_to 'Supprimer', pokemon,
			method: :delete,
			data: {confirm: 'Etes-vous sûr de vouloir supprimer ce Pokemon ?'},
			class: 'btn btn-danger' %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<% else %>
<p>Il n'y a pas encore de Pokémon.</p>
<% end %>

<p>
	<%= link_to 'Ajouter un Pokemon', new_pokemon_path, class: 'btn btn-success' %>
</p>

app/views/pokemons/new.html.erb
<h1>Ajout d'un Pokemon</h1>

<%= render partial: 'form', locals: {submit: 'Ajouter'} %> <!-- Préférer l'internationalisation pour le nom du bouton -->

<%= link_to 'Liste des Pokemons', pokemons_path, class: 'btn btn-primary' %>

app/views/pokemons/show.html.erb
<h1>Afficher un Pokémon</h1>

<p>Numéro : #<%= sprintf '%03d', @pokemon.number %></p>
<p>Nom : <%= @pokemon.name %></p>
<p>Niveau : <%= @pokemon.level %></p>
<p>Point de vie : <%= @pokemon.health_points %></p>

<p>
	Type:
	<% type = @pokemon.type %>
	<% if type.nil? %>
	aucun
	<% else %>
	<%= type ? type_badge(type) : '&empty;'.html_safe %>
	<% end %>
</p>

<p>
  <strong>Attaques:</strong>
  <%= render partial: 'moves_list', locals: {moves: @pokemon.moves} %>
</p>

<!--
Syntaxe alternatif :

<% @pokemon.moves.each do |move| %>
<%= move.name %>
<% end %>
-->

<p>
	<%= link_to 'Liste des Pokemons', pokemons_path, class: 'btn btn-primary' %>
	<%= link_to 'Modifier le Pokemon', edit_pokemon_path, class: 'btn btn-primary' %>
</p>

app/views/types/_form.html.erb
<%= form_for @type do |f| %>
<div class="row">
  <div class="form-group col-lg-5">
    <p>
      <%= f.label :name, 'Nom' %>
      <%= f.text_field :name, class: 'form-control' %>
    </p>
  </div>
</div>
<div class="row">
  <div class="form-group col-lg-5">
    <p>
      <%= f.label :color, 'Couleur' %>
      <%= f.text_field :color, class: 'form-control' %>
    </p>
  </div>
</div>
<p>
  <%= f.submit submit , class: 'btn btn-primary' %>
</p>
<% end %>

app/views/types/edit.html.erb
<h1>Modification d'un Type</h1>

<%= render partial: 'form', locals: {submit: 'Modifier'} %>

<%= link_to 'Liste des Types', types_path, class: 'btn btn-primary' %>

app/views/types/index.html.erb
<p>
  <%= link_to 'Pokemons', pokemons_path, class: 'btn btn-default' %>
  <%= link_to 'Types', types_path, class: 'btn btn-default' %>
  <%= link_to 'Moves', moves_path, class: 'btn btn-default' %>
</p>

<h1>Types</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= type_badge(type, type.color) %></td>
        <td><%= link_to 'Afficher', type, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Modifier', edit_type_path(type), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Supprimer', type, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter un Type', new_type_path, class: 'btn btn-success' %>

app/views/types/new.html.erb
<h1>Ajout d'un Type</h1>

<%= render partial: 'form', locals: {submit: 'Ajouter'} %>

<%= link_to 'Liste des Types', types_path, class: 'btn btn-primary' %>

app/views/types/show.html.erb
<h1>Afficher un Type</h1>

<p>Nom : <%= @type.name %></p>
<p>Couleur : <%= type_badge(@type, @type.color) %></p>

<p>
	<%= link_to 'Liste des Types', types_path, class: 'btn btn-primary' %>
	<%= link_to 'Modifier le Type', edit_type_path, class: 'btn btn-primary' %>
</p>